name: Env Variable Job

on: [push]

jobs:
    job1 :
      name : On commit master branch
      runs-on: ubuntu-latest #On which machine we should run the job *
      env:
        USER_NAME: Praveen soni
        MESSAGE: Welcome to Github Actions Env
      steps :
        - uses: actions/checkout@v2
        - name: Print Env  variables  from yml
          run : | 
               echo ${{ env.USER_NAME }} 
               echo ${{ env.MESSAGE }}
                echo ${{ secrets.TOKEN }} 
              