name: Dependent Simple Job

on: [push]

jobs:
  job1 :
    name : Job One #Job name Optional
    runs-on: ubuntu-latest #On which machine we should run the job *
    steps :
      - uses: actions/checkout@v2
      - name: Print Evn variables 
        run : env | sort

  job2 :
    needs: job3
    name : Job Two Dependent on job Three
    runs-on: windows-latest #On which machine we should run the job *
    steps :
      - uses: actions/checkout@v2
      - name: Print Evn variables windows
        run : "Get-ChildItem C:"      

  job3 :
    name : Job Three #Job name Optional
    runs-on: ubuntu-latest #On which machine we should run the job *
    steps :
      - uses: actions/checkout@v2
      - name: Print Evn variables 
        run : env | sort
            