name: Simple Job

on: [push]

jobs:

   job1 :
      name : Job One
      runs-on: ubuntu-latest
      steps:
       - uses: actions/checkout@v1
       - name: Print env details STEP 2
         run: env | sort