name: Simple Job

on: [push]

jobs:
  job1 :
    name : Job One #Job name Optional
    runs-on: ubuntu-latest #On which machine we should run the job *
    steps :
      - uses: actions/checkout@v2
      - name: Print Evn variables 
        run : env | sort

  job2 :
    name : Job Two #Job name Optional
    runs-on: windows-latest #On which machine we should run the job *
    steps :
      - uses: actions/checkout@v2
      - name: Print Evn variables windows
        run : "Get-ChildItem C:"      

            